/**
 * Generates the `aus-emergency-dispatcher-objects` MSFS package that ships with
 * the app and is auto-installed into the user's Community folder, so every
 * operator sees the same scene objects with no configuration.
 *
 * The models are ORIGINAL low-poly meshes assembled from coloured boxes — a
 * shared, consistent baseline that reads at a glance (a red sedan, a white
 * ambulance with a light bar, a hi-vis figure, a rescue boat) without any
 * third-party assets. Nothing here is downloaded or redistributed: everything
 * is generated by this script and is free for all users. See CREDITS.txt.
 *
 * A model is spawned at runtime with SimConnect `AICreateSimulatedObject`, which
 * only accepts *Dynamic* SimObjects — hence `category = SimpleObject` and a
 * WindsockAssistance base container. If a sim rejects one, the injector's title
 * chain (scenes.ts) falls back to the base-game `Windsock`.
 *
 * Run: `node resources/msfs-packages/_build.mjs`
 */
import { mkdirSync, writeFileSync, rmSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, 'aus-emergency-dispatcher-objects');

rmSync(ROOT, { recursive: true, force: true });

// ---- palette ----------------------------------------------------------
const C = {
  red: [0.72, 0.11, 0.11],
  fireRed: [0.78, 0.06, 0.06],
  rescueOrange: [0.95, 0.42, 0.05],
  hiVis: [0.98, 0.55, 0.04],
  hiVisGreen: [0.55, 0.85, 0.1],
  amber: [0.98, 0.72, 0.05],
  white: [0.92, 0.92, 0.92],
  ltGrey: [0.7, 0.7, 0.72],
  silver: [0.78, 0.8, 0.83],
  dkGrey: [0.25, 0.25, 0.27],
  charred: [0.14, 0.14, 0.15],
  rust: [0.4, 0.26, 0.16],
  black: [0.06, 0.06, 0.07],
  tyre: [0.08, 0.08, 0.09],
  glass: [0.12, 0.16, 0.2],
  policeBlue: [0.06, 0.12, 0.5],
  navy: [0.12, 0.16, 0.3],
  skin: [0.82, 0.62, 0.5],
  blue: [0.1, 0.3, 0.75],
  fireYellow: [0.95, 0.78, 0.12],
  ember: [0.85, 0.28, 0.04],
  smokeDk: [0.16, 0.16, 0.17],
  smokeMd: [0.32, 0.32, 0.34],
  smokeLt: [0.5, 0.5, 0.52],
};

// ---- geometry -------------------------------------------------------
// A box: centre x/z, bottom y, size L(x)×H(y)×W(z), optional yaw about vertical.
function faceBox(cx, by, cz, L, H, W, yawDeg = 0) {
  const x = L / 2;
  const z = W / 2;
  const y0 = by;
  const y1 = by + H;
  const yaw = (yawDeg * Math.PI) / 180;
  const cs = Math.cos(yaw);
  const sn = Math.sin(yaw);
  const P = (lx, ly, lz) => [cx + (lx * cs - lz * sn), ly, cz + (lx * sn + lz * cs)];
  const RN = (n) => [n[0] * cs - n[2] * sn, n[1], n[0] * sn + n[2] * cs];
  const faces = [
    { n: [0, 1, 0], v: [P(-x, y1, -z), P(x, y1, -z), P(x, y1, z), P(-x, y1, z)] },
    { n: [0, -1, 0], v: [P(-x, y0, z), P(x, y0, z), P(x, y0, -z), P(-x, y0, -z)] },
    { n: [0, 0, 1], v: [P(-x, y0, z), P(-x, y1, z), P(x, y1, z), P(x, y0, z)] },
    { n: [0, 0, -1], v: [P(x, y0, -z), P(x, y1, -z), P(-x, y1, -z), P(-x, y0, -z)] },
    { n: [1, 0, 0], v: [P(x, y0, z), P(x, y1, z), P(x, y1, -z), P(x, y0, -z)] },
    { n: [-1, 0, 0], v: [P(-x, y0, -z), P(-x, y1, -z), P(-x, y1, z), P(-x, y0, z)] },
  ];
  const pos = [];
  const nrm = [];
  const idx = [];
  faces.forEach((f, fi) => {
    const rn = RN(f.n);
    f.v.forEach((p) => {
      pos.push(...p);
      nrm.push(...rn);
    });
    const b = fi * 4;
    idx.push(b, b + 1, b + 2, b, b + 2, b + 3);
  });
  return { pos, nrm, idx };
}

/** wheel-set helper: four boxes at ±halfTrack / ±wheelBase */
function wheels(wheelBase, halfTrack, r, w) {
  const out = [];
  for (const sx of [1, -1]) for (const sz of [1, -1]) {
    out.push({ box: [sx * wheelBase, 0, sz * halfTrack, r * 2, r * 1.6, w], col: C.tyre });
  }
  return out;
}

// ---- model builder -------------------------------------------------
function modelGltf(name, parts) {
  const groups = new Map();
  for (const p of parts) {
    const key = p.col.join(',');
    if (!groups.has(key)) groups.set(key, { col: p.col, pos: [], nrm: [], idx: [] });
    const g = groups.get(key);
    const base = g.pos.length / 3;
    const b = faceBox(...p.box);
    for (const v of b.pos) g.pos.push(v);
    for (const v of b.nrm) g.nrm.push(v);
    for (const i of b.idx) g.idx.push(i + base);
  }

  const pad = (buf) => (buf.length % 4 ? Buffer.concat([buf, Buffer.alloc(4 - (buf.length % 4))]) : buf);
  const bins = [];
  const bufferViews = [];
  const accessors = [];
  const materials = [];
  const primitives = [];
  let off = 0;
  let mi = 0;

  for (const g of groups.values()) {
    const posBuf = pad(Buffer.from(new Float32Array(g.pos).buffer));
    const nrmBuf = pad(Buffer.from(new Float32Array(g.nrm).buffer));
    const idxBuf = pad(Buffer.from(new Uint16Array(g.idx).buffer));

    const posView = bufferViews.length;
    bufferViews.push({ buffer: 0, byteOffset: off, byteLength: g.pos.length * 4, target: 34962 });
    off += posBuf.length;
    const nrmView = bufferViews.length;
    bufferViews.push({ buffer: 0, byteOffset: off, byteLength: g.nrm.length * 4, target: 34962 });
    off += nrmBuf.length;
    const idxView = bufferViews.length;
    bufferViews.push({ buffer: 0, byteOffset: off, byteLength: g.idx.length * 2, target: 34963 });
    off += idxBuf.length;
    bins.push(posBuf, nrmBuf, idxBuf);

    const mn = [1e9, 1e9, 1e9];
    const mx = [-1e9, -1e9, -1e9];
    for (let i = 0; i < g.pos.length; i += 3)
      for (let k = 0; k < 3; k++) {
        mn[k] = Math.min(mn[k], g.pos[i + k]);
        mx[k] = Math.max(mx[k], g.pos[i + k]);
      }

    const posAcc = accessors.length;
    accessors.push({ bufferView: posView, componentType: 5126, count: g.pos.length / 3, type: 'VEC3', min: mn, max: mx });
    const nrmAcc = accessors.length;
    accessors.push({ bufferView: nrmView, componentType: 5126, count: g.nrm.length / 3, type: 'VEC3' });
    const idxAcc = accessors.length;
    accessors.push({ bufferView: idxView, componentType: 5123, count: g.idx.length, type: 'SCALAR' });

    materials.push({
      name: `${name}_m${mi}`,
      pbrMetallicRoughness: { baseColorFactor: [...g.col, 1], metallicFactor: 0, roughnessFactor: 0.85 },
      doubleSided: true,
    });
    primitives.push({ attributes: { POSITION: posAcc, NORMAL: nrmAcc }, indices: idxAcc, material: mi, mode: 4 });
    mi++;
  }

  const bin = Buffer.concat(bins);
  const gltf = {
    asset: { version: '2.0', generator: 'AED model builder', minVersion: '2.0' },
    extensionsUsed: [],
    extensionsRequired: [],
    scene: 0,
    scenes: [{ nodes: [0] }],
    nodes: [{ mesh: 0, name }],
    meshes: [{ name, primitives }],
    materials: materials.map((m) => ({ ...m, alphaMode: 'OPAQUE' })),
    buffers: [{ uri: `${name}.bin`, byteLength: bin.length }],
    bufferViews,
    accessors,
  };
  return { gltf: JSON.stringify(gltf, null, 1), bin };
}

// ---- models -------------------------------------------------------
// Convention: +x forward, +y up, +z right; the object sits on y = 0.

function sedan(bodyCol, extras = []) {
  return [
    { box: [0, 0.24, 0, 4.4, 0.72, 1.78], col: bodyCol },
    { box: [-0.25, 0.94, 0, 2.4, 0.6, 1.6], col: bodyCol },
    { box: [0.92, 0.95, 0, 0.14, 0.55, 1.5], col: C.glass }, // windscreen
    { box: [-1.4, 0.95, 0, 0.12, 0.5, 1.46], col: C.glass }, // rear glass
    ...wheels(1.4, 0.85, 0.34, 0.28),
    ...extras,
  ];
}

const MODELS = [
  { title: 'AED_Car', desc: 'Sedan (red)', parts: sedan(C.red) },
  {
    title: 'AED_Car4x4',
    desc: '4x4 / SUV (blue)',
    parts: [
      { box: [0, 0.32, 0, 4.7, 1.0, 1.92], col: C.blue },
      { box: [-0.1, 1.32, 0, 2.7, 0.72, 1.82], col: C.blue },
      { box: [1.05, 1.34, 0, 0.14, 0.62, 1.7], col: C.glass },
      { box: [-1.5, 1.34, 0, 0.12, 0.58, 1.66], col: C.glass },
      { box: [-0.1, 2.04, 0, 2.3, 0.09, 1.6], col: C.dkGrey }, // roof rack
      ...wheels(1.5, 0.9, 0.42, 0.34),
    ],
  },
  {
    title: 'AED_Wreck',
    desc: 'Crashed vehicle',
    parts: [
      { box: [-0.2, 0.14, 0, 3.9, 0.5, 1.82], col: C.charred, yaw: 3 },
      { box: [1.55, 0.1, 0, 1.1, 0.32, 1.66], col: C.rust }, // crushed front
      { box: [-0.4, 0.58, 0, 1.7, 0.34, 1.55], col: C.charred, yaw: 6 }, // collapsed cabin
      { box: [1.0, 0.6, 0, 0.12, 0.28, 1.4], col: C.glass },
      { box: [1.5, 1.0, 0, 0.35, 1.3, 0.35], col: C.smokeMd, yaw: 10 }, // engine-bay smoke
      { box: [1.75, 2.1, 0.2, 0.6, 1.2, 0.6], col: C.smokeLt, yaw: -14 },
      { box: [2.3, 0.03, 0.9, 0.5, 0.06, 0.5], col: C.tyre }, // wheel off
      { box: [-1.3, 0, 0.82, 0.6, 0.5, 0.26], col: C.tyre },
      { box: [-1.3, 0, -0.82, 0.6, 0.5, 0.26], col: C.tyre },
      { box: [1.3, 0, -0.82, 0.6, 0.5, 0.26], col: C.tyre },
    ],
  },
  {
    title: 'AED_Truck',
    desc: 'Rigid truck',
    parts: [
      { box: [0, 0.5, 0, 8.6, 0.32, 2.4], col: C.black }, // chassis
      { box: [3.2, 0.82, 0, 1.9, 1.9, 2.45], col: C.fireYellow }, // cab
      { box: [4.06, 1.34, 0, 0.12, 0.8, 2.2], col: C.glass },
      { box: [-1.4, 0.82, 0, 5.6, 2.3, 2.5], col: C.ltGrey }, // box body
      ...[3.4, -0.6, -2.7].flatMap((wx) => [
        { box: [wx, 0, 1.12, 0.9, 0.85, 0.34], col: C.tyre },
        { box: [wx, 0, -1.12, 0.9, 0.85, 0.34], col: C.tyre },
      ]),
    ],
  },
  {
    title: 'AED_Ambulance',
    desc: 'Ambulance',
    parts: [
      { box: [-0.3, 0.48, 0, 5.4, 2.0, 2.34], col: C.white }, // box body
      { box: [2.6, 0.48, 0, 1.5, 1.6, 2.3], col: C.white }, // cab
      { box: [3.35, 1.16, 0, 0.12, 0.7, 2.1], col: C.glass },
      { box: [-0.3, 0.95, 1.18, 5.4, 0.42, 0.03], col: C.red }, // side stripe
      { box: [-0.3, 0.95, -1.18, 5.4, 0.42, 0.03], col: C.red },
      { box: [-0.3, 0.55, 1.18, 5.4, 0.4, 0.03], col: C.hiVisGreen }, // battenberg
      { box: [-0.3, 0.55, -1.18, 5.4, 0.4, 0.03], col: C.hiVisGreen },
      { box: [1.0, 2.48, 0.42, 1.0, 0.16, 0.72], col: C.blue }, // light bar
      { box: [1.0, 2.48, -0.42, 1.0, 0.16, 0.72], col: C.red },
      ...wheels(1.9, 1.05, 0.4, 0.36),
    ],
  },
  {
    title: 'AED_FireTruck',
    desc: 'Fire appliance',
    parts: [
      { box: [0, 0.48, 0, 8.0, 0.4, 2.5], col: C.black },
      { box: [-1.0, 0.9, 0, 5.4, 1.9, 2.55], col: C.fireRed }, // pump body
      { box: [3.0, 0.9, 0, 2.0, 1.9, 2.55], col: C.fireRed }, // cab
      { box: [4.0, 1.62, 0, 0.12, 0.8, 2.3], col: C.glass },
      { box: [-1.0, 0.95, 1.29, 3.2, 1.1, 0.05], col: C.silver }, // pump panel
      { box: [-1.0, 0.95, -1.29, 3.2, 1.1, 0.05], col: C.silver },
      { box: [-0.5, 2.95, 0, 7.2, 0.18, 0.5], col: C.silver }, // ladder
      { box: [3.0, 2.95, 0.4, 1.2, 0.16, 0.7], col: C.red }, // light bar
      { box: [3.0, 2.95, -0.4, 1.2, 0.16, 0.7], col: C.blue },
      ...[3.0, -1.2, -3.0].flatMap((wx) => [
        { box: [wx, 0, 1.16, 0.95, 0.9, 0.38], col: C.tyre },
        { box: [wx, 0, -1.16, 0.95, 0.9, 0.38], col: C.tyre },
      ]),
    ],
  },
  {
    title: 'AED_PoliceCar',
    desc: 'Police vehicle',
    parts: sedan(C.white, [
      { box: [0, 0.4, 0.9, 2.0, 0.5, 0.03], col: C.policeBlue }, // door blocks
      { box: [0, 0.4, -0.9, 2.0, 0.5, 0.03], col: C.policeBlue },
      { box: [1.45, 0.61, 0, 1.2, 0.04, 1.5], col: C.policeBlue }, // bonnet
      { box: [-0.1, 1.58, 0.32, 1.05, 0.16, 0.72], col: C.policeBlue }, // light bar
      { box: [-0.1, 1.58, -0.32, 1.05, 0.16, 0.72], col: C.red },
    ]),
  },
  {
    title: 'AED_Boat',
    desc: 'Rescue vessel',
    parts: [
      { box: [-0.3, 0.18, 0, 5.6, 0.7, 2.1], col: C.rescueOrange }, // hull
      { box: [2.7, 0.22, 0, 1.2, 0.55, 1.4], col: C.rescueOrange, yaw: 0 }, // bow
      { box: [-0.3, 0.88, 0, 5.0, 0.12, 1.9], col: C.ltGrey }, // deck
      { box: [-0.5, 1.0, 0, 1.7, 1.0, 1.4], col: C.white }, // console
      { box: [0.35, 1.3, 0, 0.1, 0.55, 1.2], col: C.glass },
      { box: [-3.0, 0.32, 0, 0.5, 0.8, 0.5], col: C.black }, // outboard
      { box: [-0.6, 2.0, 0, 0.09, 0.9, 0.09], col: C.ltGrey }, // mast
      { box: [-0.6, 2.85, 0, 0.16, 0.12, 0.16], col: C.blue }, // nav light
    ],
  },
  {
    title: 'AED_Cordon',
    desc: 'Cordon / tape stand',
    parts: [
      { box: [0, 0, 0, 0.45, 0.05, 0.45], col: C.dkGrey }, // foot
      { box: [0, 0, 0, 0.09, 0.95, 0.09], col: C.dkGrey }, // post
      { box: [0.42, 0.82, 0, 0.9, 0.09, 0.03], col: C.policeBlue }, // tape
      { box: [0, 1.0, 0, 0.15, 0.15, 0.15], col: C.amber }, // beacon
    ],
  },
  {
    title: 'AED_SpotFire',
    desc: 'Spot fire with drifting smoke',
    parts: [
      { box: [0, 0, 0, 1.7, 0.15, 1.7], col: C.charred }, // burnt ground
      { box: [0, 0.05, 0, 1.0, 0.75, 1.0], col: C.ember, yaw: 12 }, // flame base
      { box: [0, 0.6, 0, 0.7, 0.7, 0.7], col: C.fireRed, yaw: -22 }, // flame mid
      { box: [0, 1.15, 0, 0.42, 0.6, 0.42], col: C.hiVis, yaw: 28 }, // flame
      { box: [0, 1.65, 0, 0.24, 0.5, 0.24], col: C.fireYellow, yaw: -10 }, // flame tip
      // leaning smoke plume — drifts downwind (+x) and widens with height
      { box: [0.25, 1.5, 0.1, 0.95, 1.1, 0.95], col: C.smokeDk, yaw: 18 },
      { box: [0.7, 2.5, 0.2, 1.35, 1.2, 1.35], col: C.smokeMd, yaw: -14 },
      { box: [1.35, 3.6, 0.35, 1.85, 1.4, 1.85], col: C.smokeLt, yaw: 22 },
    ],
  },
  {
    title: 'AED_FireSeat',
    desc: 'Main fire — flame front and tall smoke column',
    parts: [
      { box: [0, 0, 0, 5.5, 0.2, 5.5], col: C.charred }, // burnt ground
      // flame front: a row of flames
      ...[-1.6, 0, 1.6].flatMap((fz) => [
        { box: [0, 0.05, fz, 1.6, 1.3, 1.4], col: C.ember, yaw: 10 },
        { box: [0, 1.0, fz, 1.1, 1.2, 1.0], col: C.fireRed, yaw: -18 },
        { box: [0, 1.9, fz, 0.7, 1.0, 0.7], col: C.hiVis, yaw: 24 },
        { box: [0, 2.6, fz, 0.4, 0.8, 0.4], col: C.fireYellow, yaw: -8 },
      ]),
      // tall leaning smoke column (~16 m), widening + drifting downwind
      { box: [0.4, 2.4, 0, 3.2, 2.2, 3.4], col: C.smokeDk, yaw: 12 },
      { box: [1.2, 4.4, 0.3, 4.6, 2.4, 4.6], col: C.smokeDk, yaw: -10 },
      { box: [2.6, 6.6, 0.7, 6.0, 2.6, 6.0], col: C.smokeMd, yaw: 16 },
      { box: [4.6, 9.0, 1.1, 7.4, 2.8, 7.2], col: C.smokeMd, yaw: -12 },
      { box: [7.2, 11.6, 1.6, 8.6, 3.0, 8.4], col: C.smokeLt, yaw: 14 },
      { box: [10.5, 14.4, 2.0, 9.6, 3.2, 9.2], col: C.smokeLt, yaw: -8 },
    ],
  },
  { title: 'AED_Casualty', desc: 'Casualty / bystander (hi-vis)', parts: figure(C.hiVis) },
  { title: 'AED_Medic', desc: 'Responder / paramedic (green hi-vis)', parts: figure(C.hiVisGreen) },
  {
    title: 'AED_Patient',
    desc: 'Patient (supine, on a stretcher)',
    parts: [
      { box: [0, 0.55, 0, 2.1, 0.12, 0.75], col: C.ltGrey }, // stretcher
      { box: [0, 0, 0.42, 0.06, 0.55, 0.06], col: C.dkGrey },
      { box: [0, 0, -0.42, 0.06, 0.55, 0.06], col: C.dkGrey },
      { box: [-0.7, 0, 0.42, 0.06, 0.55, 0.06], col: C.dkGrey },
      { box: [-0.7, 0, -0.42, 0.06, 0.55, 0.06], col: C.dkGrey },
      { box: [0.1, 0.67, 0, 1.7, 0.28, 0.55], col: C.red }, // blanket
      { box: [0.85, 0.7, 0, 0.22, 0.22, 0.22], col: C.skin }, // head
    ],
  },
];

/** upright human figure ~1.75 m, hi-vis torso */
function figure(vestCol) {
  return [
    { box: [0, 0, 0.11, 0.26, 0.85, 0.17], col: C.navy }, // leg
    { box: [0, 0, -0.11, 0.26, 0.85, 0.17], col: C.navy },
    { box: [0, 0.85, 0, 0.42, 0.62, 0.27], col: vestCol }, // torso
    { box: [0, 0.9, 0.29, 0.16, 0.55, 0.14], col: vestCol }, // arm
    { box: [0, 0.9, -0.29, 0.16, 0.55, 0.14], col: vestCol },
    { box: [0, 1.5, 0, 0.21, 0.24, 0.21], col: C.skin }, // head
  ];
}

// ---- write package ----------------------------------------------------
mkdirSync(ROOT, { recursive: true });

writeFileSync(
  path.join(ROOT, 'manifest.json'),
  JSON.stringify(
    {
      dependencies: [],
      content_type: 'MISC',
      title: 'Aus Emergency Dispatcher — Scene Objects',
      manufacturer: 'Aus Emergency Dispatcher',
      creator: 'Aus Emergency Dispatcher',
      package_version: '1.3.0',
      minimum_game_version: '1.0.0',
      release_notes: { neutral: { LastUpdate: '', OlderHistory: '' } },
    },
    null,
    2,
  ),
);

const layout = { content: [] };
// MSFS layout.json `date` is a Windows FILETIME (100 ns ticks since 1601-01-01).
// A real value (not 0) keeps the sim from treating the package as stale/invalid.
const FILETIME = BigInt(Date.now()) * 10000n + 116444736000000000n;
function addFile(rel, buf) {
  const abs = path.join(ROOT, rel);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, buf);
  layout.content.push({ path: rel.replace(/\\/g, '/'), size: buf.length, date: Number(FILETIME) });
}

// NOTE: MSFS rejects a Community package that has ANY unexpected file at its
// root, so this package contains ONLY manifest.json + layout.json + SimObjects/.
// (Credits live in the repo and in Documents\Aus Emergency Dispatcher\CREDITS.md.)

// Minimal, spec-correct sim.cfg for a scenery prop that SimConnect
// `AICreateSimulatedObject` will spawn: [Version] + [General] category=SimpleObject
// (a "Dynamic" SimObject) + [fltsim.0] with just a title and a model folder.
// NO base_container (the old relative path was invalid and broke the object) and
// no aircraft-only keys.
function simCfg(m) {
  return (
    `[Version]\nmajor = 1\nminor = 0\n\n` +
    `[General]\ncategory = SimpleObject\n\n` +
    `[fltsim.0]\ntitle = ${m.title}\nmodel = \ntexture = \n` +
    `description = ${m.desc} (Aus Emergency Dispatcher)\n`
  );
}

for (const m of MODELS) {
  const { gltf, bin } = modelGltf(m.title, m.parts);
  const base = `SimObjects/${m.title}`;
  addFile(`${base}/model/${m.title}.gltf`, Buffer.from(gltf));
  addFile(`${base}/model/${m.title}.bin`, bin);
  addFile(`${base}/model/model.cfg`, Buffer.from(`[MODELS]\nnormal = ${m.title}.gltf\n`));
  addFile(`${base}/sim.cfg`, Buffer.from(simCfg(m)));
}

writeFileSync(path.join(ROOT, 'layout.json'), JSON.stringify(layout, null, 2));

console.log(`Built ${MODELS.length} models -> ${ROOT}`);
console.log('Titles:', MODELS.map((m) => m.title).join(', '));
